[project]
name = "flux0-core"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "aiorwlock>=1.5.0",
    "nanoid>=2.0.0",
    "structlog>=25.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = []

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = [
  "."
]
