[project]
name = "flux0-server"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "flux0-api",
    "pydantic-settings>=2.8.1",
    "toml>=0.10.2",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
flux0-api = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "types-toml>=0.10.8.20240310",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = [
  "."
]
