[project]
name = "flux0-cli"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "flux0-client",
    "jsonpath-ng>=1.7.0",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
flux0-client = { git = "https://github.com/flux0-ai/flux0-client-python" }
